config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "flights#index"
  resources :flights , only: :index
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: "departing_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight

  has_many :passengers
  accepts_nested_attributes_for :passengers, allow_destroy: true
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departing_airport, class_name: "Airport", foreign_key: "departing_airport_id"
    belongs_to :arrival_airport, class_name: "Airport", foreign_key: "arrival_airport_id"

    has_many :bookings
    has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_one :flight, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    params[:passengers].to_i.times{ @booking.passengers.build }
    @flight = Flight.find( params[:flight_id] )
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
        @booking.passengers.each do |p|
          PassengerMailer.confirmation_email(p).deliver_later
        end
        redirect_to @booking, notice: "You have sucessfully booked the flight!"
    else
        render :new, status: :unprocessable_entity  
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map{|a| [a.code, a.id] }
    @dates = Flight.all.map{ |f| f.date}.uniq
    
    if !params.has_key?(:arrival_airport)
      @results = nil
    elsif [params[:departing_airport].blank?, params[:arrival_airport].blank?, params[:date].blank?].all?
      flash.now[:error] = "Please select at least one of the three options"
    else
      @results = Flight.where({departing_airport: params[:departing_airport], arrival_airport: params[:arrival_airport]}.reject{ |_, v| v.blank? }) 
    end

  end

  private
  def search_params
    params.permit(:departing_airport, :passengers, :arrival_airport, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div><strong>Flight ID : <%= @flight.id %></strong></div> 
<div>Arrival Airport : <%= @flight.arrival_airport.code %> </div>
<div>Departing Airport : <%= @flight.departing_airport.code %> </div>
<div>Date : <%= @flight.date.to_date %> Time : <%= @flight.date.strftime("%H:%M")%></div>

<h4>Please enter Passenger(s) info: </h4>
<%= form_with model: @booking do |f| %>
  <%= f.hidden_field :flight_id, value: @flight.id %>

  <%= f.fields_for :passengers do |sub_form| %>
    <div>
        <%= sub_form.text_field :name,placeholder: "Passenger name" %>
        <%= sub_form.text_field :email,placeholder: "Passenger email" %>
    </div>
    <br>
  <% end %>
  <%= f.submit "Create Booking" %>
<% end%>

app/views/bookings/show.html.erb
<% if notice %>
  <%= notice %>
<% end %>

<h2>Flight Information : </h2>
<div>
<% @booking.passengers.each_with_index do |passenger, i| %>
    <div class="m-2">
    <div class="my-3 fw-bold"><%= "Passenger #{i + 1}" %></div>
    <div class="my-3"><%= "Name: #{passenger.name}" %></div>
    <div class="my-3"><%= "Email: #{passenger.email}" %></div>
    </div>
<% end %>
</div>

<div class="text-center">
  <%= link_to "Search for more flights", flights_path%>
</div>

app/views/flights/_results.html.erb
<% if @results.empty? %>

    <h3>No flights available for the given criteria</h3>

<% else %>
    <h3> Please select a flight : </h3>
    <hr>

    <%= form_with url: new_booking_path, method: :get do |f| %>

        <% @results.each do |flight|%>
            <%= radio_button_tag(:flight_id, flight.id) %>
            <label><%= "#{flight.arrival_airport.code} to #{flight.departing_airport.code} on #{flight.date.to_date}" %></label>
            <br>
        <% end %>

        <%= f.hidden_field :passengers, value: params[:passengers] %>
        <%= f.submit "Select flight"%>

    <% end %>

<% end %>

app/views/flights/_search.html.erb
<h2>Search flights:</h2>

<div class="container">
    <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>">
        <h4><%= message %></h4>
    </div>
    <% end %>
</div>
<%= form_with url: flights_path, method: :get do |f|%>
    <label>Departure : </label>
    <%= f.select :departing_airport, @airport_options ,prompt: "Departure Airport"%>
    <label>Arrival : </label>
    <%= f.select :arrival_airport, @airport_options ,prompt: "Arrival Airport"%>
    <label>Date : </label>
    <%= f.select :date, @dates, prompt: "Select a date"%>
    <label>No. of Passengers : </label>
    <%= f.select :passengers, (1..4) %>
    <%= f.submit value: "Search"%>
<% end %>

app/views/flights/index.html.erb
<%= render "search" %>

<% unless @results.nil? %>
    <%= render "results" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>